local ReplicatedStorage = game:GetService('ReplicatedStorage')
require(ReplicatedStorage:WaitForChild('Modules'))
require(ReplicatedStorage:WaitForChild('Core'))
local ServerStorage = game:GetService('ServerStorage')
require(ServerStorage:WaitForChild('Modules'))
require(ServerStorage:WaitForChild('Core'))
